export const UPDATE_PHOTOGRAPH_LIST = 'UPDATE_PHOTOGRAPH_LIST';
export const UPDATE_CATEGORY_LIST = 'UPDATE_CATEGORY_LIST';
export const FETCH_PHOTOGRAPH_LIST ='FETCH_PHOTOGRAPH_LIST';
export const FETCH_CATEGORY_LIST ='FETCH_CATEGORY_LIST';